name: Daily Employee PDF Report

on:
  schedule:
    - cron: "10 16 * * *"
      timezone: "Pacific/Auckland"

  workflow_dispatch:

jobs:
  generate-report:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Generate and send daily report
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}

          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}

          REPORT_EMAIL_1: ${{ secrets.REPORT_EMAIL_1 }}
          REPORT_EMAIL_2: ${{ secrets.REPORT_EMAIL_2 }}
          REPORT_EMAIL_CC: ${{ secrets.REPORT_EMAIL_CC }}

        run: |
          python scheduled_report.py
