EMAIL_ADDRESS = "karthicdr.nz@gmail.com"
EMAIL_PASSWORD = "oxgk dmgl hhnm lqkc"
REPORT_EMAIL_1 = "karthic.rajkumar8@gmail.com"
REPORT_EMAIL_2 = "roshni10august@gmail.com"
REPORT_EMAIL_CC = "roshniaugust10@gmail.com"
